def require($condition; $message): if $condition then . else error($message) end;
.[0] as $m | .[1] as $c
| require($m.schema_version == 1 and $c.schema_version == 1; "Invalid schema version")
| require($m.scope == $c.scope; "Report scopes differ")
| require(all($m.packages[]; (.purl | type) == "string" and (.purl | test("^pkg:[a-z][a-z0-9.+-]*/[^/?#[:space:]]+(/[^/?#[:space:]]+)*(\\?[^#[:space:]]+)?(#[^[:space:]]+)?$"))); "Invalid package identity")
| require(($m.expected_packages - [$m.packages[].purl] | length) == 0; "A configured package is absent")
| require(all($m.packages[]; .resolved_revision == null or (.resolved_revision | test("^[0-9a-f]{40}$|^[0-9a-f]{64}$"))); "Invalid checkout revision")
| require(all($m.packages[]; all(.overlay_evidence[]; . as $e | any($m.evidence[]; .logical == $e.file and .sha256 == $e.sha256))); "Invalid overlay evidence")
| require(all($m.targets[]; all(.dependencies[]; .target as $t | any($m.targets[]; .label == $t))); "Invalid dependency reference")
| require(all($m.targets[]; all(.packages[]; . as $p | any($m.packages[]; .purl == $p))); "Invalid package reference")
| require(all($m.roots[]; . as $root | any($m.targets[]; .label == $root)); "Invalid root reference")
| require(all($m.evidence[]; (.sha256 | test("^[0-9a-f]{64}$")) and (.logical | startswith("/") | not)); "Invalid evidence record")
| require(all($m.packages[]; all((.license_evidence + .notice_evidence)[]; . as $e | any($m.evidence[]; .logical == $e.file and .sha256 == $e.sha256 and (.content | type) == "string"))); "Invalid license evidence")
| require(all($m.unassigned_license_evidence[]; . as $e | any($m.evidence[]; .logical == $e.file and .sha256 == $e.sha256 and (.content | type) == "string")); "Invalid unassigned license evidence")
| require(all(($ARGS.named.required_overlay_packages // [])[]; . as $p | any($m.packages[]; .purl == $p and (.overlay_evidence | length) > 0)); "Missing overlay evidence")
| require(($c.conflicting_declarations | length) == 0; "Conflicting declarations")
| require(($c.missing_license_text | sort) == ([$m.packages[] | select((.license_evidence | length) == 0) | .purl] | unique); "License coverage differs")
| require($c.missing_identities == ([$m.targets[] | select(.helper == false and .kind != "source_file" and (.packages | length) == 0) | .label] | unique); "Identity coverage differs")
| require($c.unresolved_terms == ([$m.packages[] | select((.declared_licenses | length) == 0) | .purl] | unique); "Terms coverage differs")
| {schema_version: 1, scope: $m.scope, valid: true}
